file = open("40lines.txt", "r")
file_content = file.read()
copy = open("copy.txt", "w")
copy.write(file_content)
file.close()
copy.close()
copy = open("copy.txt", "r")
file = open("40lines.txt", "r")
file_result = file.read()
copy_result = copy.read()
if file_result == copy_result:
    print("Same")
file.close()
copy.close()
